# Generated by Django 4.2.1 on 2023-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=256)),
                ('lanzamiento', models.DateField(max_length=20)),
                ('clasificacion', models.IntegerField()),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FreeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PayGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=256)),
                ('lanzamiento', models.DateField(max_length=20)),
                ('clasificacion', models.IntegerField()),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
        ),
    ]
