# Generated by Django 4.2.1 on 2023-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygames',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
