# Generated by Django 4.2.1 on 2023-05-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegosApp', '0003_alter_paygames_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freegames',
            name='costo',
        ),
    ]
