# Generated by Django 4.2.1 on 2023-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosApp', '0004_remove_freegames_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygames',
            name='imagen',
            field=models.ImageField(null=True, upload_to='juegos-pagos'),
        ),
    ]
